export const CATEGORIES = [
  "Artificial Intelligence & Machine Learning",
  "Software Development & Programming",
  "Web Development",
  "UI/UX & Product Design",
  "Graphic Design & Visual Arts",
  "Video, Photography & Creative Media",
  "Digital Marketing",
  "Content Creation & Creator Economy",
  "Data & Analytics",
  "Cybersecurity",
  "Cloud Computing & DevOps",
  "No-Code, Low-Code & Automation",
  "Business & Entrepreneurship",
  "E-commerce",
  "Sales",
  "Finance & FinTech",
  "Productivity & Digital Tools",
  "Education & Online Teaching",
  "Blockchain & Web3",
  "IT & Technology",
  "Emerging Digital Skills",
  "Professional Digital Skills",
  "Other"
];

export const SKILLS_BY_CATEGORY: Record<string, { id: string; name: string }[]> = {
  "Artificial Intelligence & Machine Learning": [
    { id: "ai-ai", name: "Artificial Intelligence (AI)" },
    { id: "ai-generative", name: "Generative AI" },
    { id: "ai-automation", name: "AI Automation" },
    { id: "ai-agents", name: "AI Agents" },
    { id: "ai-prompt", name: "Prompt Engineering" },
    { id: "ai-content", name: "AI-Assisted Content Creation" },
    { id: "ai-coding", name: "AI-Assisted Coding" },
    { id: "ai-research", name: "AI Research" },
    { id: "ml", name: "Machine Learning" },
    { id: "ml-deep", name: "Deep Learning" },
    { id: "nlp", name: "Natural Language Processing (NLP)" },
    { id: "cv", name: "Computer Vision" },
    { id: "rl", name: "Reinforcement Learning" },
    { id: "llm", name: "Large Language Models (LLMs)" },
    { id: "rag", name: "Retrieval-Augmented Generation (RAG)" },
    { id: "ai-model-dev", name: "AI Model Development" },
    { id: "ai-api", name: "AI API Integration" },
    { id: "ai-workflow", name: "AI Workflow Design" },
    { id: "ai-chatbot", name: "AI Chatbot Development" },
    { id: "ai-product", name: "AI Product Development" },
    { id: "ai-business", name: "AI for Business" },
    { id: "ai-marketing", name: "AI for Marketing" },
    { id: "ai-education", name: "AI for Education" },
    { id: "ai-finance", name: "AI for Finance" }
  ],
  "Software Development & Programming": [
    { id: "prog-fundamentals", name: "Programming Fundamentals" },
    { id: "prog-python", name: "Python" },
    { id: "prog-javascript", name: "JavaScript" },
    { id: "prog-typescript", name: "TypeScript" },
    { id: "prog-java", name: "Java" },
    { id: "prog-c", name: "C" },
    { id: "prog-cpp", name: "C++" },
    { id: "prog-csharp", name: "C#" },
    { id: "prog-go", name: "Go" },
    { id: "prog-rust", name: "Rust" },
    { id: "prog-php", name: "PHP" },
    { id: "prog-ruby", name: "Ruby" },
    { id: "prog-kotlin", name: "Kotlin" },
    { id: "prog-swift", name: "Swift" },
    { id: "prog-dart", name: "Dart" },
    { id: "prog-r", name: "R Programming" },
    { id: "prog-matlab", name: "MATLAB" },
    { id: "prog-sql", name: "SQL" },
    { id: "prog-html", name: "HTML" },
    { id: "prog-css", name: "CSS" },
    { id: "prog-git", name: "Git & GitHub" },
    { id: "prog-software-eng", name: "Software Engineering" },
    { id: "prog-oop", name: "Object-Oriented Programming" },
    { id: "prog-fp", name: "Functional Programming" },
    { id: "prog-data-structures", name: "Data Structures & Algorithms" },
    { id: "prog-api-dev", name: "API Development" },
    { id: "prog-backend", name: "Backend Development" },
    { id: "prog-frontend", name: "Frontend Development" },
    { id: "prog-fullstack", name: "Full-Stack Development" },
    { id: "prog-web-dev", name: "Web Development" },
    { id: "prog-mobile", name: "Mobile App Development" },
    { id: "prog-desktop", name: "Desktop App Development" },
    { id: "prog-game", name: "Game Development" },
    { id: "prog-embedded", name: "Embedded Systems" },
    { id: "prog-systems", name: "Systems Programming" }
  ],
  "Web Development": [
    { id: "web-design", name: "Website Design" },
    { id: "web-responsive", name: "Responsive Web Design" },
    { id: "web-landing", name: "Landing Page Design" },
    { id: "web-frontend", name: "Frontend Development" },
    { id: "web-backend", name: "Backend Development" },
    { id: "web-fullstack", name: "Full-Stack Web Development" },
    { id: "web-react", name: "React" },
    { id: "web-nextjs", name: "Next.js" },
    { id: "web-vue", name: "Vue.js" },
    { id: "web-angular", name: "Angular" },
    { id: "web-svelte", name: "Svelte" },
    { id: "web-node", name: "Node.js" },
    { id: "web-express", name: "Express.js" },
    { id: "web-wordpress", name: "WordPress" },
    { id: "web-webflow", name: "Webflow" },
    { id: "web-framer", name: "Framer" },
    { id: "web-wix", name: "Wix" },
    { id: "web-shopify", name: "Shopify Development" },
    { id: "web-accessibility", name: "Web Accessibility" },
    { id: "web-performance", name: "Web Performance" },
    { id: "web-pwa", name: "Progressive Web Apps (PWA)" },
    { id: "web-ecommerce", name: "E-commerce Development" },
    { id: "web-cms", name: "CMS Development" }
  ],
  "UI/UX & Product Design": [
    { id: "ui-design", name: "UI Design" },
    { id: "ux-design", name: "UX Design" },
    { id: "uiux-design", name: "UI/UX Design" },
    { id: "product-design", name: "Product Design" },
    { id: "interaction-design", name: "Interaction Design" },
    { id: "user-research", name: "User Research" },
    { id: "design-thinking", name: "Design Thinking" },
    { id: "design-systems", name: "Design Systems" },
    { id: "wireframing", name: "Wireframing" },
    { id: "prototyping", name: "Prototyping" },
    { id: "usability-testing", name: "Usability Testing" },
    { id: "information-architecture", name: "Information Architecture" },
    { id: "mobile-app-design", name: "Mobile App Design" },
    { id: "web-design", name: "Web Design" },
    { id: "dashboard-design", name: "Dashboard Design" },
    { id: "figma", name: "Figma" },
    { id: "adobe-xd", name: "Adobe XD" },
    { id: "sketch", name: "Sketch" },
    { id: "canva", name: "Canva" },
    { id: "framer-design", name: "Framer Design" }
  ],
  "Graphic Design & Visual Arts": [
    { id: "graphic-design", name: "Graphic Design" },
    { id: "logo-design", name: "Logo Design" },
    { id: "brand-identity", name: "Brand Identity Design" },
    { id: "typography", name: "Typography" },
    { id: "illustration", name: "Illustration" },
    { id: "digital-illustration", name: "Digital Illustration" },
    { id: "print-design", name: "Print Design" },
    { id: "poster-design", name: "Poster Design" },
    { id: "flyer-design", name: "Flyer Design" },
    { id: "brochure-design", name: "Brochure Design" },
    { id: "packaging-design", name: "Packaging Design" },
    { id: "infographic-design", name: "Infographic Design" },
    { id: "presentation-design", name: "Presentation Design" },
    { id: "social-media-design", name: "Social Media Design" },
    { id: "photo-editing", name: "Photo Editing" },
    { id: "adobe-photoshop", name: "Adobe Photoshop" },
    { id: "adobe-illustrator", name: "Adobe Illustrator" },
    { id: "adobe-indesign", name: "Adobe InDesign" },
    { id: "coreldraw", name: "CorelDRAW" },
    { id: "canva-design", name: "Canva Design" }
  ],
  "Video, Photography & Creative Media": [
    { id: "video-editing", name: "Video Editing" },
    { id: "film-editing", name: "Film Editing" },
    { id: "cinematography", name: "Cinematography" },
    { id: "videography", name: "Videography" },
    { id: "photography", name: "Photography" },
    { id: "mobile-photography", name: "Mobile Photography" },
    { id: "product-photography", name: "Product Photography" },
    { id: "portrait-photography", name: "Portrait Photography" },
    { id: "adobe-premiere", name: "Adobe Premiere Pro" },
    { id: "adobe-aftereffects", name: "Adobe After Effects" },
    { id: "davinci-resolve", name: "DaVinci Resolve" },
    { id: "final-cut-pro", name: "Final Cut Pro" },
    { id: "capcut", name: "CapCut" },
    { id: "motion-graphics", name: "Motion Graphics" },
    { id: "2d-animation", name: "2D Animation" },
    { id: "3d-animation", name: "3D Animation" },
    { id: "vfx", name: "Visual Effects (VFX)" },
    { id: "motion-design", name: "Motion Design" },
    { id: "video-production", name: "Video Production" },
    { id: "youtube-production", name: "YouTube Video Production" },
    { id: "live-streaming", name: "Live Streaming" },
    { id: "podcast-production", name: "Podcast Production" },
    { id: "audio-editing", name: "Audio Editing" },
    { id: "sound-design", name: "Sound Design" }
  ],
  "Digital Marketing": [
    { id: "digital-marketing", name: "Digital Marketing" },
    { id: "social-media-marketing", name: "Social Media Marketing" },
    { id: "social-media-management", name: "Social Media Management" },
    { id: "content-marketing", name: "Content Marketing" },
    { id: "email-marketing", name: "Email Marketing" },
    { id: "seo", name: "Search Engine Optimization (SEO)" },
    { id: "sem", name: "Search Engine Marketing (SEM)" },
    { id: "google-ads", name: "Google Ads" },
    { id: "meta-ads", name: "Meta Ads" },
    { id: "tiktok-ads", name: "TikTok Ads" },
    { id: "linkedin-marketing", name: "LinkedIn Marketing" },
    { id: "influencer-marketing", name: "Influencer Marketing" },
    { id: "affiliate-marketing", name: "Affiliate Marketing" },
    { id: "performance-marketing", name: "Performance Marketing" },
    { id: "growth-marketing", name: "Growth Marketing" },
    { id: "marketing-analytics", name: "Marketing Analytics" },
    { id: "cro", name: "Conversion Rate Optimization (CRO)" },
    { id: "lead-generation", name: "Lead Generation" },
    { id: "marketing-automation", name: "Marketing Automation" },
    { id: "marketing-strategy", name: "Marketing Strategy" },
    { id: "community-management", name: "Community Management" },
    { id: "online-advertising", name: "Online Advertising" }
  ],
  "Content Creation & Creator Economy": [
    { id: "content-creation", name: "Content Creation" },
    { id: "content-strategy", name: "Content Strategy" },
    { id: "copywriting", name: "Copywriting" },
    { id: "creative-writing", name: "Creative Writing" },
    { id: "technical-writing", name: "Technical Writing" },
    { id: "blogging", name: "Blogging" },
    { id: "scriptwriting", name: "Scriptwriting" },
    { id: "storytelling", name: "Storytelling" },
    { id: "youtube-content", name: "YouTube Content Creation" },
    { id: "podcasting", name: "Podcasting" },
    { id: "newsletter-creation", name: "Newsletter Creation" },
    { id: "social-media-content", name: "Social Media Content Creation" },
    { id: "personal-branding", name: "Personal Branding" },
    { id: "creator-branding", name: "Creator Branding" },
    { id: "ugc-content", name: "UGC Content Creation" },
    { id: "digital-publishing", name: "Digital Publishing" },
    { id: "ebook-creation", name: "E-book Creation" }
  ],
  "Data & Analytics": [
    { id: "data-analysis", name: "Data Analysis" },
    { id: "data-science", name: "Data Science" },
    { id: "data-visualization", name: "Data Visualization" },
    { id: "business-intelligence", name: "Business Intelligence" },
    { id: "statistical-analysis", name: "Statistical Analysis" },
    { id: "predictive-analytics", name: "Predictive Analytics" },
    { id: "data-engineering", name: "Data Engineering" },
    { id: "data-cleaning", name: "Data Cleaning" },
    { id: "data-mining", name: "Data Mining" },
    { id: "big-data", name: "Big Data" },
    { id: "excel", name: "Excel" },
    { id: "advanced-excel", name: "Advanced Excel" },
    { id: "power-bi", name: "Microsoft Power BI" },
    { id: "tableau", name: "Tableau" },
    { id: "looker-studio", name: "Looker Studio" },
    { id: "google-sheets", name: "Google Sheets" },
    { id: "sql-analytics", name: "SQL Analytics" },
    { id: "python-data-analysis", name: "Python for Data Analysis" },
    { id: "ml-analytics", name: "Machine Learning Analytics" },
    { id: "dashboard-development", name: "Dashboard Development" }
  ],
  "Cybersecurity": [
    { id: "cybersecurity", name: "Cybersecurity" },
    { id: "information-security", name: "Information Security" },
    { id: "network-security", name: "Network Security" },
    { id: "cloud-security", name: "Cloud Security" },
    { id: "application-security", name: "Application Security" },
    { id: "web-security", name: "Web Security" },
    { id: "ethical-hacking", name: "Ethical Hacking" },
    { id: "penetration-testing", name: "Penetration Testing" },
    { id: "vulnerability-assessment", name: "Vulnerability Assessment" },
    { id: "digital-forensics", name: "Digital Forensics" },
    { id: "security-operations", name: "Security Operations" },
    { id: "incident-response", name: "Incident Response" },
    { id: "identity-access-management", name: "Identity & Access Management" },
    { id: "cryptography", name: "Cryptography" },
    { id: "security-awareness", name: "Security Awareness" },
    { id: "risk-management", name: "Cybersecurity Risk Management" }
  ],
  "Cloud Computing & DevOps": [
    { id: "cloud-computing", name: "Cloud Computing" },
    { id: "aws", name: "Amazon Web Services (AWS)" },
    { id: "azure", name: "Microsoft Azure" },
    { id: "gcp", name: "Google Cloud Platform (GCP)" },
    { id: "cloud-architecture", name: "Cloud Architecture" },
    { id: "cloud-administration", name: "Cloud Administration" },
    { id: "cloud-security", name: "Cloud Security" },
    { id: "devops", name: "DevOps" },
    { id: "devsecops", name: "DevSecOps" },
    { id: "ci-cd", name: "CI/CD" },
    { id: "docker", name: "Docker" },
    { id: "kubernetes", name: "Kubernetes" },
    { id: "terraform", name: "Terraform" },
    { id: "infrastructure-as-code", name: "Infrastructure as Code" },
    { id: "linux-admin", name: "Linux Administration" },
    { id: "server-admin", name: "Server Administration" },
    { id: "sre", name: "Site Reliability Engineering (SRE)" },
    { id: "system-admin", name: "System Administration" }
  ],
  "No-Code, Low-Code & Automation": [
    { id: "no-code-dev", name: "No-Code Development" },
    { id: "low-code-dev", name: "Low-Code Development" },
    { id: "workflow-automation", name: "Workflow Automation" },
    { id: "business-process-automation", name: "Business Process Automation" },
    { id: "n8n", name: "n8n" },
    { id: "zapier", name: "Zapier" },
    { id: "make", name: "Make" },
    { id: "power-automate", name: "Microsoft Power Automate" },
    { id: "airtable", name: "Airtable" },
    { id: "notion", name: "Notion" },
    { id: "bubble", name: "Bubble" },
    { id: "webflow-lowcode", name: "Webflow" },
    { id: "glide", name: "Glide" },
    { id: "softr", name: "Softr" },
    { id: "retool", name: "Retool" },
    { id: "ai-automation-lowcode", name: "AI Automation" },
    { id: "api-automation", name: "API Automation" },
    { id: "crm-automation", name: "CRM Automation" },
    { id: "marketing-automation", name: "Marketing Automation" }
  ],
  "Business & Entrepreneurship": [
    { id: "entrepreneurship", name: "Entrepreneurship" },
    { id: "business-management", name: "Business Management" },
    { id: "business-strategy", name: "Business Strategy" },
    { id: "business-development", name: "Business Development" },
    { id: "startup-development", name: "Startup Development" },
    { id: "product-management", name: "Product Management" },
    { id: "project-management", name: "Project Management" },
    { id: "operations-management", name: "Operations Management" },
    { id: "business-analysis", name: "Business Analysis" },
    { id: "strategic-planning", name: "Strategic Planning" },
    { id: "leadership", name: "Leadership" },
    { id: "team-management", name: "Team Management" },
    { id: "customer-experience", name: "Customer Experience" },
    { id: "customer-success", name: "Customer Success" },
    { id: "sales-management", name: "Sales Management" },
    { id: "negotiation", name: "Negotiation" },
    { id: "decision-making", name: "Decision Making" },
    { id: "problem-solving", name: "Problem Solving" }
  ],
  "E-commerce": [
    { id: "ecommerce", name: "E-commerce" },
    { id: "shopify", name: "Shopify" },
    { id: "woocommerce", name: "WooCommerce" },
    { id: "online-store-dev", name: "Online Store Development" },
    { id: "ecommerce-marketing", name: "E-commerce Marketing" },
    { id: "product-listing", name: "Product Listing" },
    { id: "product-photography", name: "Product Photography" },
    { id: "ecommerce-seo", name: "E-commerce SEO" },
    { id: "ecommerce-advertising", name: "E-commerce Advertising" },
    { id: "dropshipping", name: "Dropshipping" },
    { id: "print-on-demand", name: "Print-on-Demand" },
    { id: "ecommerce-automation", name: "E-commerce Automation" },
    { id: "marketplace-management", name: "Marketplace Management" },
    { id: "conversion-optimization", name: "Conversion Optimization" },
    { id: "customer-retention", name: "Customer Retention" }
  ],
  "Sales": [
    { id: "sales", name: "Sales" },
    { id: "digital-sales", name: "Digital Sales" },
    { id: "b2b-sales", name: "B2B Sales" },
    { id: "b2c-sales", name: "B2C Sales" },
    { id: "sales-strategy", name: "Sales Strategy" },
    { id: "lead-generation", name: "Lead Generation" },
    { id: "prospecting", name: "Prospecting" },
    { id: "cold-email", name: "Cold Email" },
    { id: "cold-calling", name: "Cold Calling" },
    { id: "sales-funnels", name: "Sales Funnels" },
    { id: "sales-copywriting", name: "Sales Copywriting" },
    { id: "crm-management", name: "CRM Management" },
    { id: "account-management", name: "Account Management" },
    { id: "business-development", name: "Business Development" },
    { id: "negotiation-sales", name: "Negotiation" },
    { id: "closing-techniques", name: "Closing Techniques" }
  ],
  "Finance & FinTech": [
    { id: "personal-finance", name: "Personal Finance" },
    { id: "financial-literacy", name: "Financial Literacy" },
    { id: "financial-management", name: "Financial Management" },
    { id: "accounting", name: "Accounting" },
    { id: "bookkeeping", name: "Bookkeeping" },
    { id: "financial-analysis", name: "Financial Analysis" },
    { id: "financial-modeling", name: "Financial Modeling" },
    { id: "investment-fundamentals", name: "Investment Fundamentals" },
    { id: "fintech", name: "FinTech" },
    { id: "digital-payments", name: "Digital Payments" },
    { id: "cryptocurrency", name: "Cryptocurrency" },
    { id: "blockchain", name: "Blockchain" },
    { id: "web3", name: "Web3" },
    { id: "defi", name: "DeFi" },
    { id: "nft-development", name: "NFT Development" },
    { id: "blockchain-development", name: "Blockchain Development" }
  ],
  "Productivity & Digital Tools": [
    { id: "digital-productivity", name: "Digital Productivity" },
    { id: "microsoft-office", name: "Microsoft Office" },
    { id: "microsoft-word", name: "Microsoft Word" },
    { id: "microsoft-excel", name: "Microsoft Excel" },
    { id: "microsoft-powerpoint", name: "Microsoft PowerPoint" },
    { id: "google-workspace", name: "Google Workspace" },
    { id: "google-docs", name: "Google Docs" },
    { id: "google-sheets", name: "Google Sheets" },
    { id: "google-slides", name: "Google Slides" },
    { id: "notion-tool", name: "Notion" },
    { id: "trello", name: "Trello" },
    { id: "asana", name: "Asana" },
    { id: "clickup", name: "ClickUp" },
    { id: "slack", name: "Slack" },
    { id: "project-management-tools", name: "Project Management Tools" },
    { id: "time-management", name: "Time Management" },
    { id: "remote-work", name: "Remote Work" },
    { id: "digital-organization", name: "Digital Organization" },
    { id: "personal-knowledge-management", name: "Personal Knowledge Management" }
  ],
  "Education & Online Teaching": [
    { id: "online-teaching", name: "Online Teaching" },
    { id: "instructional-design", name: "Instructional Design" },
    { id: "course-creation", name: "Course Creation" },
    { id: "e-learning-development", name: "E-learning Development" },
    { id: "educational-technology", name: "Educational Technology" },
    { id: "curriculum-development", name: "Curriculum Development" },
    { id: "training-development", name: "Training & Development" },
    { id: "technology-teaching", name: "Teaching with Technology" },
    { id: "lms", name: "Learning Management Systems" },
    { id: "online-course-marketing", name: "Online Course Marketing" },
    { id: "educational-content-creation", name: "Educational Content Creation" },
    { id: "tutoring-technology", name: "Tutoring Technology" }
  ],
  "Blockchain & Web3": [
    { id: "blockchain", name: "Blockchain" },
    { id: "web3", name: "Web3" },
    { id: "smart-contracts", name: "Smart Contracts" },
    { id: "solidity", name: "Solidity" },
    { id: "ethereum-dev", name: "Ethereum Development" },
    { id: "dapps", name: "Decentralized Applications (dApps)" },
    { id: "cryptocurrency", name: "Cryptocurrency" },
    { id: "defi", name: "DeFi" },
    { id: "nft-development", name: "NFT Development" },
    { id: "dao-development", name: "DAO Development" },
    { id: "web3-product-dev", name: "Web3 Product Development" },
    { id: "blockchain-security", name: "Blockchain Security" }
  ],
  "IT & Technology": [
    { id: "information-technology", name: "Information Technology" },
    { id: "computer-networking", name: "Computer Networking" },
    { id: "network-administration", name: "Network Administration" },
    { id: "it-support", name: "IT Support" },
    { id: "technical-support", name: "Technical Support" },
    { id: "hardware-troubleshooting", name: "Hardware Troubleshooting" },
    { id: "database-administration", name: "Database Administration" },
    { id: "systems-administration", name: "Systems Administration" },
    { id: "it-project-management", name: "IT Project Management" },
    { id: "it-service-management", name: "IT Service Management" },
    { id: "database-development", name: "Database Development" },
    { id: "software-testing", name: "Software Testing" },
    { id: "qa", name: "Quality Assurance (QA)" },
    { id: "test-automation", name: "Test Automation" }
  ],
  "Emerging Digital Skills": [
    { id: "xr", name: "Extended Reality (XR)" },
    { id: "vr", name: "Virtual Reality (VR)" },
    { id: "ar", name: "Augmented Reality (AR)" },
    { id: "mr", name: "Mixed Reality (MR)" },
    { id: "spatial-computing", name: "Spatial Computing" },
    { id: "robotics", name: "Robotics" },
    { id: "iot", name: "Internet of Things (IoT)" },
    { id: "digital-twins", name: "Digital Twins" },
    { id: "3d-modeling", name: "3D Modeling" },
    { id: "3d-printing", name: "3D Printing" },
    { id: "metaverse-development", name: "Metaverse Development" },
    { id: "quantum-computing", name: "Quantum Computing" },
    { id: "edge-computing", name: "Edge Computing" },
    { id: "autonomous-systems", name: "Autonomous Systems" },
    { id: "emerging-research", name: "Emerging Technology Research" }
  ],
  "Professional Digital Skills": [
    { id: "remote-work", name: "Remote Work" },
    { id: "virtual-assistance", name: "Virtual Assistance" },
    { id: "digital-project-management", name: "Digital Project Management" },
    { id: "digital-operations", name: "Digital Operations" },
    { id: "research-skills", name: "Research Skills" },
    { id: "online-research", name: "Online Research" },
    { id: "presentation-skills", name: "Presentation Skills" },
    { id: "professional-communication", name: "Professional Communication" },
    { id: "technical-communication", name: "Technical Communication" },
    { id: "digital-collaboration", name: "Digital Collaboration" },
    { id: "freelancing", name: "Freelancing" },
    { id: "remote-freelancing", name: "Remote Freelancing" },
    { id: "portfolio-development", name: "Portfolio Development" },
    { id: "career-development", name: "Career Development" },
    { id: "linkedin-optimization", name: "LinkedIn Optimization" },
    { id: "resume-design", name: "Resume/CV Design" },
    { id: "personal-branding-pro", name: "Personal Branding" }
  ],
  "Other": []
};

export const ALL_SKILLS = Object.values(SKILLS_BY_CATEGORY).flat();
  "AI Automation",
  'Technology',
  'Business',
  'Design',
  'Marketing',
  'Personal Development',
  'Creative Arts',
  'Health & Fitness'
];

export const SKILLS_BY_CATEGORY: Record<string, { id: string, name: string }[]> = {
  'Technology': [
    { id: 'tech-web-dev', name: 'Web Development' },
    { id: 'tech-data-sci', name: 'Data Science' },
    { id: 'tech-mobile', name: 'Mobile Development' },
    { id: 'tech-cyber', name: 'Cybersecurity' },
    { id: 'tech-cloud', name: 'Cloud Computing' }
  ],
  'Business': [
    { id: 'biz-entrepreneurship', name: 'Entrepreneurship' },
    { id: 'biz-management', name: 'Management' },
    { id: 'biz-finance', name: 'Finance' },
    { id: 'biz-sales', name: 'Sales' }
  ],
  'Design': [
    { id: 'design-ui-ux', name: 'UI/UX Design' },
    { id: 'design-graphic', name: 'Graphic Design' },
    { id: 'design-3d', name: '3D Modeling' },
    { id: 'design-animation', name: 'Animation' }
  ],
  'Marketing': [
    { id: 'mkt-digital', name: 'Digital Marketing' },
    { id: 'mkt-seo', name: 'SEO' },
    { id: 'mkt-social', name: 'Social Media' },
    { id: 'mkt-content', name: 'Content Marketing' }
  ],
  'Personal Development': [
    { id: 'pd-productivity', name: 'Productivity' },
    { id: 'pd-leadership', name: 'Leadership' },
    { id: 'pd-communication', name: 'Communication' }
  ],
  'Creative Arts': [
    { id: 'art-photography', name: 'Photography' },
    { id: 'art-music', name: 'Music Production' },
    { id: 'art-writing', name: 'Creative Writing' }
  ],
  'Health & Fitness': [
    { id: 'health-nutrition', name: 'Nutrition' },
    { id: 'health-fitness', name: 'Fitness Training' },
    { id: 'health-wellness', name: 'Wellness & Mental Health' }
  ]
};

export const ALL_SKILLS = Object.values(SKILLS_BY_CATEGORY).flat();
