/**
 * ALEX Workflow Orchestrator
 * 
 * Integrates the new AI-driven orchestration layer with the existing workflow infrastructure
 * Bridges between AIOrchestrator and the artifact generation system
 */

import { AIOrchestrator } from './ai-orchestrator'
import { 
  AlexNextAction, 
  AutomationPlan, 
  ConversationContext, 
  OrchestrationResult 
} from './types'
import { ArtifactService } from '../artifact-generation/artifact-service'
import { ArchitectureDesigner } from '../artifact-generation/architecture-designer'
import { AutomationSpec } from '../artifact-generation/automation-spec'
import { OrchestrationQuestionService } from './orchestration-question-service'

export interface WorkflowOrchestrationRequest {
  conversationId: string
  userId: string
  userMessage: string
  conversationHistory: Array<{ role: string; content: string }>
  mode: string
  attachedFiles?: any[]
}

export interface WorkflowOrchestrationResponse {
  status: string
  message: string
  action: AlexNextAction // Native AI action - NOT converted to question format
  needsInput?: boolean
  architectureProposal?: any
  artifacts?: any[]
  specification?: AutomationSpec
  plan?: AutomationPlan
}

export class WorkflowOrchestrator {
  private static instance: WorkflowOrchestrator
  private aiOrchestrator: AIOrchestrator
  
  private constructor() {
    this.aiOrchestrator = AIOrchestrator.getInstance()
  }
  
  static getInstance(): WorkflowOrchestrator {
    if (!WorkflowOrchestrator.instance) {
      WorkflowOrchestrator.instance = new WorkflowOrchestrator()
    }
    return WorkflowOrchestrator.instance
  }
  
  /**
   * Main orchestration entry point
   * Replaces WorkflowManagerV2.processRequest for AI-driven behavior
   */
  async orchestrateWorkflow(request: WorkflowOrchestrationRequest): Promise<WorkflowOrchestrationResponse> {
    console.log('[Workflow Orchestrator] ===== ORCHESTRATION START =====')
    console.log('[Workflow Orchestrator] Request:', {
      conversationId: request.conversationId,
      userId: request.userId,
      message: request.userMessage.substring(0, 100),
      mode: request.mode
    })
    
    // Load conversation context
    const context: ConversationContext = {
      conversationId: request.conversationId,
      userId: request.userId,
      messages: request.conversationHistory.map(m => ({
        role: m.role as 'user' | 'assistant',
        content: m.content,
        timestamp: new Date().toISOString()
      })),
      mode: request.mode as any
    }
    
    // Load current automation plan if exists
    const currentPlan = await this.loadCurrentPlan(request.conversationId, request.userId)
    
    // Let AI decide what to do
    const orchestrationResult = await this.aiOrchestrator.orchestrate(
      request.userMessage,
      context,
      currentPlan
    )
    
    console.log('[Workflow Orchestrator] Orchestration result:', {
      actionType: orchestrationResult.action.type,
      intent: orchestrationResult.intent,
      confidence: orchestrationResult.confidence,
      hasUpdatedPlan: !!orchestrationResult.updatedPlan
    })
    
    // P1: Removed QuestionTracker override to preserve AI authority
    // QuestionTracker is now advisory only, not authoritative
    // The AI decides what to do next, not the tracker
    console.log('[P1] QuestionTracker status: advisory (does not override AI decisions)')
    
    // Handle the AI's decision
    return await this.handleOrchestrationResult(
      orchestrationResult,
      request,
      currentPlan
    )
  }
  
  /**
   * Handle the orchestration result and execute the appropriate action
   * P0: Preserve native AI action instead of converting to question format
   */
  private async handleOrchestrationResult(
    result: OrchestrationResult,
    request: WorkflowOrchestrationRequest,
    currentPlan: AutomationPlan | null
  ): Promise<WorkflowOrchestrationResponse> {
    const { action, updatedPlan } = result
    
    console.log('[P0] Native AI action preserved:', action.type)
    
    // Save updated plan if provided
    if (updatedPlan) {
      await this.savePlan(request.conversationId, request.userId, updatedPlan, action.type)
    }
    
    // CRITICAL FIX: Also save plan when action contains plan (for plan action type)
    // This ensures plans generated by AI are persisted for confirmation flows
    if (action.type === 'plan' && action.plan) {
      console.log('[Workflow Orchestrator] Saving plan from action.plan for plan action')
      await this.savePlan(request.conversationId, request.userId, action.plan, action.type)
    }
    
    // CRITICAL FIX: Ensure build exists for plan actions
    // This creates the build record if it doesn't exist, enabling plan persistence
    if (action.type === 'plan' && action.plan) {
      console.log('[Workflow Orchestrator] Ensuring build exists for plan action')
      const existingBuild = await ArtifactService.getActiveBuild(request.conversationId, request.userId)
      if (!existingBuild) {
        console.log('[Workflow Orchestrator] Creating new build for plan action')
        await ArtifactService.createBuild(
          request.conversationId,
          request.userId,
          action.plan.objective || request.userMessage,
          'workflow'
        )
      }
    }
    
    // For generate action, invoke artifact generation machinery
    if (action.type === 'generate' || action.type === 'execute') {
      console.log('[P0] Invoking artifact generation machinery for action:', action.type)
      console.log('[FORENSIC] Generate action detected')
      console.log('[FORENSIC] updatedPlan exists:', !!updatedPlan)
      console.log('[FORENSIC] action.plan exists:', !!action.plan)
      console.log('[FORENSIC] updatedPlan platform:', updatedPlan?.platform?.name)
      console.log('[FORENSIC] action.plan platform:', action.plan?.platform?.name)
      // CRITICAL FIX: Use updatedPlan if available, otherwise fall back to action.plan
      // This ensures platform updates (like "n8n") are preserved for architecture generation
      const planForGeneration = updatedPlan || action.plan
      console.log('[FORENSIC] planForGeneration platform:', planForGeneration.platform?.name || 'no platform')
      console.log('[Workflow Orchestrator] Using plan for generation:', planForGeneration.platform?.name || 'no platform')
      const generateResponse = await this.handleGenerate(planForGeneration, request)
      
      // Return generate response with the AI action preserved
      return {
        ...generateResponse,
        action: action // Preserve native AI action
      }
    }
    
    // For all other actions, return native response with AI action preserved
    switch (action.type) {
      case 'respond':
        return {
          status: 'collecting_requirements',
          message: action.message,
          action: action
        }
      
      case 'clarify':
        return {
          status: 'collecting_requirements',
          message: action.message || action.question || 'I need some information to proceed.',
          needsInput: true,
          action: action
        }
      
      case 'recommend':
        return {
          status: 'collecting_requirements',
          message: action.message || 'Here are my recommendations:',
          needsInput: true,
          action: action
        }
      
      case 'brainstorm':
        return {
          status: 'collecting_requirements',
          message: action.message || 'Here are some ideas to consider:',
          needsInput: true,
          action: action
        }
      
      case 'plan':
        return {
          status: 'planning',
          message: 'Here\'s my plan for your automation:',
          plan: action.plan,
          action: action
        }
      
      case 'revise':
        return {
          status: 'revising',
          message: action.message || 'Here\'s the revised plan:',
          plan: action.plan,
          action: action
        }
      
      default:
        console.warn('[Workflow Orchestrator] Unknown action type:', action.type)
        return {
          status: 'collecting_requirements',
          message: 'I\'m not sure how to proceed. Could you clarify?',
          action: action
        }
    }
  }
  
  /**
   * Handle artifact generation
   * Made public for explicit plan approval flow
   */
  public async handleGenerate(
    plan: AutomationPlan,
    request: WorkflowOrchestrationRequest
  ): Promise<WorkflowOrchestrationResponse> {
    console.log('[Workflow Orchestrator] Generating artifact from plan')
    console.log('[Workflow Orchestrator] Plan platform:', plan.platform?.name || 'no platform')
    
    // Convert plan to AutomationSpec (legacy compatibility)
    const spec = this.planToSpec(plan)
    
    // Design architecture
    const architecture = await ArchitectureDesigner.design(spec)
    
    // Create or update build
    const existingBuild = await ArtifactService.getActiveBuild(request.conversationId, request.userId)
    
    let build
    if (existingBuild) {
      // Update existing build
      await ArtifactService.updateSpecification(existingBuild.id, spec, [])
      await ArtifactService.updateBuildStatus(existingBuild.id, 'designing_architecture')
      build = existingBuild
    } else {
      // Create new build
      build = await ArtifactService.createBuild(
        request.conversationId,
        request.userId,
        request.userMessage,
        'workflow'
      )
      await ArtifactService.updateSpecification(build.id, spec, [])
    }
    
    // Return architecture proposal
    return {
      status: 'awaiting_architecture_verification',
      message: 'I\'ve designed the architecture for your automation. Please review and confirm.',
      architectureProposal: {
        description: plan.objective,
        platform: plan.platform?.name || 'n8n',
        platformReasoning: plan.platform?.reasoning || 'Suitable for this automation',
        complexity: plan.architecture?.complexity || 'moderate',
        stages: plan.architecture?.stages || [],
        assumptions: plan.assumptions || [],
        recommendations: plan.recommendations || []
      },
      specification: spec,
      plan
    }
  }
  
  /**
   * Convert AutomationPlan to AutomationSpec (P2-B: Enhanced fidelity)
   * Explicit mapping with loss awareness and audit trail
   */
  private planToSpec(plan: AutomationPlan): AutomationSpec {
    console.log('[P2-B] Starting planToSpec conversion with enhanced fidelity')
    
    const spec: AutomationSpec = {
      automationType: 'workflow',
      description: plan.objective,
      domain: 'custom',
      aiConfig: { enabled: false },
      humanApproval: { required: false },
      errorHandling: { retryStrategy: 'exponential-backoff', maxRetries: 3 },
      persistence: { enabled: true, logLevel: 'info', auditTrail: true },
      architecture: { complexity: plan.architecture?.complexity || 'moderate' }
    }
    
    // P2-B: Explicit field mapping with loss awareness
    // PRESERVED: Core fields
    if (plan.trigger) {
      spec.trigger = {
        type: plan.trigger.type || 'manual',
        source: plan.trigger.source,
        config: plan.trigger.description
      }
    }
    
    if (plan.inputs) {
      spec.inputs = {
        sources: plan.inputs.sources || [],
        format: 'json'
      }
    }
    
    if (plan.outputs) {
      spec.outputs = {
        destinations: plan.outputs.destinations || [],
        notification: true
      }
    }
    
    if (plan.integrations) {
      spec.integrations = {
        platform: plan.integrations.platform
      }
    }
    
    if (plan.platform) {
      spec.platform = plan.platform.name
      spec.platformReasoning = plan.platform.reasoning
    }
    
    // P2-B: PRESERVED: P2-A enhanced fields
    if (plan.assumptions && plan.assumptions.length > 0) {
      spec.assumptions = plan.assumptions
      console.log('[P2-B] Preserved assumptions:', plan.assumptions.length)
    }
    
    if (plan.recommendations && plan.recommendations.length > 0) {
      spec.recommendations = plan.recommendations
      console.log('[P2-B] Preserved recommendations:', plan.recommendations.length)
    }
    
    // P2-B: PRESERVED: Structured unresolved questions with category
    if (plan.unresolvedQuestions && plan.unresolvedQuestions.length > 0) {
      spec.unresolvedBlockers = plan.unresolvedQuestions.map(q => ({
        question: q.question,
        reason: q.reason,
        priority: q.priority,
        category: 'requirement' // Default category for unresolved questions
      }))
      console.log('[P2-B] Preserved unresolved questions:', plan.unresolvedQuestions.length)
    }
    
    // P2-B: PRESERVED: Users (new field to spec)
    if (plan.users && plan.users.length > 0) {
      spec.users = plan.users
      console.log('[P2-B] Preserved users:', plan.users.length)
    }
    
    // P2-B: PRESERVED: Workflow steps (new field to spec)
    if (plan.workflow && plan.workflow.length > 0) {
      spec.workflowSteps = plan.workflow
      console.log('[P2-B] Preserved workflow steps:', plan.workflow.length)
    }
    
    // P2-B: PRESERVED: Constraints (new field to spec)
    if (plan.constraints && plan.constraints.length > 0) {
      spec.constraints = plan.constraints
      console.log('[P2-B] Preserved constraints:', plan.constraints.length)
    }
    
    // P2-B: LOG: Intentionally excluded fields (for audit trail)
    const intentionallyExcluded = [
      'inputs.description (semantic info)',
      'outputs.description (semantic info)',
      'integrations.services (specific services)',
      'integrations.description (integration context)',
      'status (runtime state)',
      'confidence (AI confidence)',
      'lastUpdated (timestamp)'
    ]
    console.log('[P2-B] Intentionally excluded fields:', intentionallyExcluded)
    
    return spec
  }
  
  /**
   * Convert AutomationSpec to AutomationPlan (reverse conversion for persistence)
   * P2-B: Enhanced to preserve new fields and handle enhanced structures
   */
  private specToPlan(spec: AutomationSpec): AutomationPlan {
    console.log('[P2-B] Starting specToPlan reverse conversion with enhanced fidelity')
    
    const plan: AutomationPlan = {
      objective: spec.description || 'Unknown automation',
      status: 'draft'
    }
    
    // Map spec fields to plan fields
    if (spec.trigger) {
      plan.trigger = {
        type: spec.trigger.type,
        source: spec.trigger.source,
        description: spec.trigger.config
      }
    }
    
    if (spec.inputs) {
      plan.inputs = {
        sources: spec.inputs.sources || [],
        description: 'Input sources'
      }
    }
    
    if (spec.outputs) {
      plan.outputs = {
        destinations: spec.outputs.destinations || [],
        description: 'Output destinations'
      }
    }
    
    if (spec.integrations) {
      plan.integrations = {
        platform: spec.integrations.platform
      }
    }
    
    if (spec.platform) {
      plan.platform = {
        name: spec.platform,
        reasoning: spec.platformReasoning || 'Platform selection'
      }
    }
    
    // P2-B: PRESERVED: Enhanced assumptions (with legacy compatibility)
    if (spec.assumptions && spec.assumptions.length > 0) {
      // Handle both new enhanced structure and legacy string array
      const isEnhanced = spec.assumptions.some(a => typeof a === 'object' && a !== null)
      if (isEnhanced) {
        plan.assumptions = spec.assumptions as any
      } else {
        // Convert legacy string array to enhanced structure
        plan.assumptions = (spec.assumptions as string[]).map(statement => ({
          statement,
          basis: 'Legacy spec conversion',
          confidence: 0.8,
          category: 'other' as const
        }))
      }
      console.log('[P2-B] Preserved assumptions in reverse conversion:', spec.assumptions.length)
    }
    
    // P2-B: PRESERVED: Enhanced recommendations (with legacy compatibility)
    if (spec.recommendations && spec.recommendations.length > 0) {
      // Handle both new enhanced structure and legacy string array
      const isEnhanced = spec.recommendations.some(r => typeof r === 'object' && r !== null)
      if (isEnhanced) {
        plan.recommendations = spec.recommendations as any
      } else {
        // Convert legacy string array to enhanced structure
        plan.recommendations = (spec.recommendations as string[]).map(statement => ({
          statement,
          reasoning: 'Legacy spec conversion',
          priority: 'medium' as const
        }))
      }
      console.log('[P2-B] Preserved recommendations in reverse conversion:', spec.recommendations.length)
    }
    
    // P2-B: PRESERVED: Structured unresolved blockers
    if (spec.unresolvedBlockers && spec.unresolvedBlockers.length > 0) {
      plan.unresolvedQuestions = spec.unresolvedBlockers.map(b => ({
        question: b.question,
        reason: b.reason,
        priority: b.priority
      }))
      console.log('[P2-B] Preserved unresolved questions in reverse conversion:', spec.unresolvedBlockers.length)
    }
    
    // P2-B: PRESERVED: Users
    if (spec.users && spec.users.length > 0) {
      plan.users = spec.users
      console.log('[P2-B] Preserved users in reverse conversion:', spec.users.length)
    }
    
    // P2-B: PRESERVED: Workflow steps
    if (spec.workflowSteps && spec.workflowSteps.length > 0) {
      plan.workflow = spec.workflowSteps
      console.log('[P2-B] Preserved workflow steps in reverse conversion:', spec.workflowSteps.length)
    }
    
    // P2-B: PRESERVED: Constraints
    if (spec.constraints && spec.constraints.length > 0) {
      plan.constraints = spec.constraints
      console.log('[P2-B] Preserved constraints in reverse conversion:', spec.constraints.length)
    }
    
    if (spec.architecture) {
      plan.architecture = {
        complexity: spec.architecture.complexity
      }
    }
    
    // Extract known fields from spec metadata if available
    if (spec._knownFields) {
      // Convert legacy string to enhanced assumption structure
      const legacyAssumption = {
        statement: `Known fields: ${spec._knownFields.join(', ')}`,
        basis: 'Legacy spec metadata',
        confidence: 1.0,
        category: 'other' as const
      }
      plan.assumptions = plan.assumptions || []
      plan.assumptions.push(legacyAssumption)
    }
    
    return plan
  }
  
  /**
   * Load current automation plan from database
   */
  private async loadCurrentPlan(
    conversationId: string,
    userId: string
  ): Promise<AutomationPlan | null> {
    try {
      const build = await ArtifactService.getActiveBuild(conversationId, userId)
      console.log('[FORENSIC] loadCurrentPlan - build exists:', !!build)
      if (build) {
        console.log('[FORENSIC] loadCurrentPlan - build.automation_plan exists:', !!build.automation_plan)
        console.log('[FORENSIC] loadCurrentPlan - build.final_specification exists:', !!build.final_specification)
        
        // First try to load from automation_plan column (new persistence)
        if (build.automation_plan) {
          console.log('[Workflow Orchestrator] Loading plan from automation_plan column')
          console.log('[FORENSIC] loadCurrentPlan - loaded from automation_plan:', (build.automation_plan as AutomationPlan).objective)
          return build.automation_plan as AutomationPlan
        }
        
        // Fallback: try to extract plan from spec (reverse of planToSpec)
        if (build.final_specification) {
          console.log('[Workflow Orchestrator] Converting spec to plan (fallback)')
          const plan = this.specToPlan(build.final_specification)
          console.log('[FORENSIC] loadCurrentPlan - loaded from spec fallback:', plan.objective)
          return plan
        }
      }
      console.log('[FORENSIC] loadCurrentPlan - no build found, returning null')
      return null
    } catch (error) {
      console.error('[Workflow Orchestrator] Failed to load plan:', error)
      console.log('[FORENSIC] loadCurrentPlan - error loading plan:', error)
      return null
    }
  }
  
  /**
   * Save automation plan to database
   */
  private async savePlan(
    conversationId: string,
    userId: string,
    plan: AutomationPlan,
    lastAction?: string
  ): Promise<void> {
    try {
      console.log('[FORENSIC] savePlan - saving plan:', plan.objective)
      console.log('[FORENSIC] savePlan - action type:', lastAction)
      
      const build = await ArtifactService.getActiveBuild(conversationId, userId)
      console.log('[FORENSIC] savePlan - build exists:', !!build)
      
      if (build) {
        // Save plan to automation_plan column (new persistence)
        const supabase = await this.getSupabaseClient()
        const { error } = await supabase
          .from('alex_artifact_builds')
          .update({
            automation_plan: plan,
            last_orchestration_action: lastAction,
            orchestration_metadata: {
              lastUpdated: new Date().toISOString(),
              action: lastAction
            },
            updated_at: new Date().toISOString()
          })
          .eq('id', build.id)
        
        if (error) {
          console.error('[Workflow Orchestrator] Failed to save plan to automation_plan column:', error)
          // Fallback: convert plan to spec and save
          const spec = this.planToSpec(plan)
          await ArtifactService.updateSpecification(build.id, spec, [])
          console.log('[Workflow Orchestrator] Plan saved via spec conversion (fallback)')
        } else {
          console.log('[Workflow Orchestrator] Plan saved to automation_plan column')
          console.log('[FORENSIC] savePlan - successfully saved to automation_plan column')
        }
      } else {
        // Create new build
        console.log('[FORENSIC] savePlan - creating new build')
        const newBuild = await ArtifactService.createBuild(
          conversationId,
          userId,
          plan.objective,
          'workflow'
        )
        
        // Save plan to new build
        const supabase = await this.getSupabaseClient()
        const { error } = await supabase
          .from('alex_artifact_builds')
          .update({
            automation_plan: plan,
            last_orchestration_action: lastAction,
            orchestration_metadata: {
              lastUpdated: new Date().toISOString(),
              action: lastAction
            },
            updated_at: new Date().toISOString()
          })
          .eq('id', newBuild.id)
        
        if (error) {
          console.error('[Workflow Orchestrator] Failed to save plan to new build:', error)
          // Fallback: convert plan to spec and save
          const spec = this.planToSpec(plan)
          await ArtifactService.updateSpecification(newBuild.id, spec, [])
          console.log('[Workflow Orchestrator] Plan saved via spec conversion (fallback)')
        } else {
          console.log('[Workflow Orchestrator] Plan saved to new build')
          console.log('[FORENSIC] savePlan - successfully saved to new build')
        }
      }
    } catch (error) {
      console.error('[Workflow Orchestrator] Failed to save plan:', error)
      console.log('[FORENSIC] savePlan - error:', error)
    }
  }
  
  /**
   * Get Supabase client for direct database access
   */
  private async getSupabaseClient() {
    const { createClient } = await import('@supabase/supabase-js')
    const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL
    const supabaseServiceRoleKey = process.env.SUPABASE_SERVICE_ROLE_KEY
    
    if (!supabaseUrl || !supabaseServiceRoleKey) {
      throw new Error('Missing Supabase environment variables')
    }
    
    return createClient(supabaseUrl, supabaseServiceRoleKey, {
      auth: {
        autoRefreshToken: false,
        persistSession: false
      }
    })
  }
}